version: "3.9"

services:
  mangashelf:
    image: ghcr.io/lammy93/mangashelf:latest
    container_name: mangashelf
    restart: unless-stopped
    user: "99:100"
    ports:
      - "8035:8080"
    volumes:
      - /mnt/user/dataz/media/books/Manga/mangas:/manga
      - /mnt/user/dataz/docker/mangashelf/data:/data
    environment:
      - TZ=Australia/Brisbane
      - SECRET_KEY=change-this-to-a-long-random-string
